# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBo7RUxcRDj-9R1lcTjjkzDajCJg8roT
"""

import plotly.graph_objects as go

import seaborn as sns

titanic = sns.load_dataset("titanic")

import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd

fig= px.scatter(titanic, x="age", y= 'fare')
fig.show()

tips = px.data.tips()

fig2= px.box(tips, x="day", y = "total_bill", title = "Box plot of total bill by day")
fig2.show()

fig3 = px.histogram(tips, x= "sex", y = "total_bill", pattern_shape ="smoker",color = "day", title ="Histogram of total bill by gender with smoker and day attribute ")
fig3.show()

iris = px.data.iris()
fig4 = px.scatter_matrix(iris, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],
                         color="species", title="Scatter Matrix of Iris Dataset")
fig4.show()

dist_data= [iris['sepal_length']]
group_labels = ['Sepal Length']
fig5= ff.create_distplot(dist_data, group_labels, show_hist = True, show_rug = False)
fig5.update_layout(title_text="Distribution Plot of Sepal Length")
fig5.show()

